### ISSUE TITLE
Option to generate key based on the physical location

### ISSUE THREAD

**Issue by davidkron** [webdeveric/webpack-assets-manifest#44]
I'm currently in the process of modernizing an existing server-side rendered application by migrating the client-side code to a asset pipeline based on webpack. To generate the appropriate paths server-side I require the help of a manifest to translate simple file paths to the effective output after webpack has built everything (including hash).

In my production build I am using a flat folder output configuration simply based on the hash of assets:

```
{
	test: /\.(png|svg|jpg|gif)$/,
	use: [
		{
			loader: 'file-loader',
			options: {
				name: '[hash].[ext]'
			}
		}
	]
}

```
The manifest plugin will generate something like this, where the key is always just the filename without any folder structure:

```
{
     "logo.png": "85626904b63ff423ce8c4357f9c92b3f.png"
}
```

This is problematic for my server-side code as I cannot resolve my files using their physical locations, e.g. `static/images/logo.png`. Another problem of the current approach is if i have a file with the same name in different locations, e.g. `static/images/hi-res/logo.png` or `static/images/low-res/logo.png`. In this case the manifest will only have one entry (because the key will just be "logo.png").

Because of such scenarios, I think it would be very useful to have an option to generate manifest keys based on the physical location of the source files (including folders) instead of just the basename of a file.

**Comment by jdb8** [comment]
@webdeveric Pretty sure this is the same issue I'm running into. I'm also trying to do something similar with a flat output directory, but changing my file-loader `name` option from `[path][name].[hash].[ext]` to `[name].[hash].[ext]` changes the *key* of the manifest file rather than just the value, which is what I expected.

E.g. `[path][name].[hash].[ext]` gives me:

```
"img/my/animation.gif": "img/my/animation.9e64d33f308cb1c2d85baba9fabb2019.gif",
```
which is fine, but I don't want to actually have the `img/my` folders present in my output dir, so changing file-loader's `name` to `[name].[hash].[ext]` seems like the way to go. But now my manifest.json looks like this:

```
"animation.gif": "animation.9e64d33f308cb1c2d85baba9fabb2019.gif",
```

which has removed it from the value too :( I'd expect:

```
"img/my/animation.gif": "animation.9e64d33f308cb1c2d85baba9fabb2019.gif",
```

instead.

I'm happy to help with a PR, but I took a quick look at the source and can't immediately see where these keys are generated... is there some logic that's basing the manifest key on the emitted asset, or something like that?

Also, if this is tricky to solve, is there any workaround I could use to get my desired manifest.json output? cc @davidkron if you solved this yourself :)

Thanks!

**Comment by unframework** [comment]
Want to chime in with similar issues (thanks for your work on this plugin, by the way!).

On my current project on occasion we have files in different folders sharing the same filename. This makes the resulting manifest JSON drop all but one of those files.

The part of code responsible for this is here: https://github.com/webdeveric/webpack-assets-manifest/blob/46757137a021085cd560f6ff3f226e51d0053d93/src/WebpackAssetsManifest.js#L547 - the "original" filename is stitched from basename of original `module.userRequest` and dirname of resulting `hashedFile` asset path.

Would be great to get both the dirname and basename out of the `module.userRequest` variable instead. Or, to avoid breaking existing expectations, could try to preserve the `module.userRequest` and pass it into `customize` callback or something?

Interested in any workarounds meanwhile. Thanks again!

**Comment by jdb8** [comment]
@unframework I think that line might be from an older version? I dug into this a little and ended up at https://github.com/webdeveric/webpack-assets-manifest/blob/051243ec8963be69ab8565b5998032cc3a020a7a/src/WebpackAssetsManifest.js#L552, but the problem is still as you say: the `originalName` ends up being dependent on the `dirname` of the output filename, which might not have any path in it (e.g. in the case where the `name` provided doesn't contain something like `[path]`).

I played around with what information we have available at that time, and we do have the `rootContext` available to us, which helps a bit: it would be possible to construct a relative path when combining that with the `userRequest` to give us something that looks decent for the key:

```js
> const path = require('path')
undefined
> let rootContext = '/tmp/tmp.hqjuLBKrio/my_app'
undefined
> let userRequest = '/tmp/tmp.hqjuLBKrio/my_app/img/my/animation.gif'
undefined
> path.relative(rootContext, userRequest)
'img/my/animation.gif'
```

Of course, this might be ignoring edge cases or possible another variable we already have access to from the loader context. I'm also not sure how other people are using the plugin so changing how these keys are created might be disruptive if people are relying on the old behaviour.

Very interested in talking more about how this approach might be fleshed out, or how we could have this work with the `customize` callback as @unframework suggested. I'm going to play around more and see if I can get something working that looks reasonable.

**Comment by jdb8** [comment]
Created a PR to implement this - let me know what you think: https://github.com/webdeveric/webpack-assets-manifest/pull/53

**Comment by webdeveric** [comment]
See https://github.com/webdeveric/webpack-assets-manifest/pull/53#issuecomment-716103746
